//Even Fibonacci Numbers

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-values terms.
 */

using EulerUtils;
using System.Runtime.InteropServices; //so i have access to MathHelper.cs

int MaxTerm = 4000000; //cap for the problem
int current = 1;
int last = 1;
int SumOfEvens = 0;

while(current < MaxTerm)
{
    Console.Write($"{current}, ");
    
    SumOfEvens += MathHelper.IsEven(current) ? current : 0;

    int temp = current;
    current += last;
    last = temp;
}

Console.WriteLine($"The sum of all evens: {SumOfEvens}");

//Console.WriteLine(MathHelper.IsEven());